package view;

import controller.BarangMasukController;
import controller.BarangKeluarController;
import model.BarangMasuk;
import model.BarangKeluar;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.List;

public class StokView extends javax.swing.JFrame {

    private BarangMasukController barangMasukController;
    private BarangKeluarController barangKeluarController;
    private DefaultTableModel model;

    /**
     * Creates new form StokView
     */
    public StokView() {
        initComponents();
        barangMasukController = new BarangMasukController();
        barangKeluarController = new BarangKeluarController();
        model = (DefaultTableModel) tblStok.getModel();
        loadData();

        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

    }

    // Method untuk memuat data barang masuk dan keluar
    private void loadData() {
        model.setRowCount(0); // Membersihkan tabel sebelum memuat data baru

        // HashMap untuk menyimpan total jumlah barang berdasarkan nama
        Map<String, Integer> stokBarang = new HashMap<>();
        Map<String, String> kategoriBarang = new HashMap<>();
        Map<String, Double> hargaBarang = new HashMap<>();
        Map<String, String> tanggalBarang = new HashMap<>();
        Map<String, String> keteranganBarang = new HashMap<>();

        // Muat data barang masuk dan akumulasi jumlah
        List<BarangMasuk> daftarBarangMasuk = barangMasukController.getDaftarBarangMasuk();
        for (BarangMasuk barang : daftarBarangMasuk) {
            String namaBarang = barang.getNamaBarang();
            stokBarang.put(namaBarang, stokBarang.getOrDefault(namaBarang, 0) + barang.getJumlah());
            kategoriBarang.put(namaBarang, barang.getKategori());
            hargaBarang.put(namaBarang, barang.getHarga());
            tanggalBarang.put(namaBarang, barang.getTanggal());
            keteranganBarang.put(namaBarang, "Masuk");
        }

        // Muat data barang keluar dan kurangi jumlah
        List<BarangKeluar> daftarBarangKeluar = barangKeluarController.getDaftarBarangKeluar();
        for (BarangKeluar barang : daftarBarangKeluar) {
            String namaBarang = barang.getNamaBarang();
            stokBarang.put(namaBarang, stokBarang.getOrDefault(namaBarang, 0) - barang.getJumlah());
            tanggalBarang.put(namaBarang, barang.getTanggal());
            keteranganBarang.put(namaBarang, "Keluar");
        }

        // Tampilkan data di tabel
        for (String namaBarang : stokBarang.keySet()) {
            model.addRow(new Object[]{
                namaBarang,
                kategoriBarang.getOrDefault(namaBarang, "-"), // Kategori
                stokBarang.get(namaBarang), // Jumlah total
                hargaBarang.getOrDefault(namaBarang, 0.0), // Harga
                tanggalBarang.getOrDefault(namaBarang, "-"), // Tanggal terakhir
                keteranganBarang.getOrDefault(namaBarang, "-") // Keterangan (Masuk/Keluar)
            });
        }
    }

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose(); // Menutup jendela saat ini
        MainView.closeInstance(); // Tutup instance yang ada
        MainView.getInstance().setVisible(true); // Buka MainView jika belum terbuka
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStok = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Stok Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N

        tblStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Barang", "Kategori", "Jumlah", "Harga", "Tanggal", "Keterangan"
            }
        ));
        jScrollPane1.setViewportView(tblStok);

        btnKeluar.setText("Keluar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStok;
    // End of variables declaration//GEN-END:variables
}
